site_name: Frads
site_description: Building lighting and energy simulation control in Python
strict: false
repo_url: https://github.com/LBNL-ETA/frads/

theme:
  name: "material"
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: white

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
  font:
    text: OpenSans
  features:
    # - navigation.tracking
    # - navigation.tabs
    # - navigation.sections
    # - navigation.indexes
    - content.tabs.link
    - content.code.annotate
    - announce.dismiss
    - navigation.tabs
    - content.code.copy
extra_css: [css/extra.css]
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

plugins:
- search
- autorefs
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          separate_signature: true
          show_source: false
          show_root_heading: true
          merge_init_into_class: true
          extra:
            member_order: source

nav:
  - Get Started:
    - Welcome to frads: index.md
    - Why frads: why.md
    - Installation: install.md
    # - Usage:
    #   - Phase Methods:
    #     - Two Phase Method: usage/phase/twophase.md
    #     - Three Phase Method: usage/phase/threephase.md
    #     - Five Phase Method: usage/phase/fivephase.md
  - How-To Guides:
    - how-to/index.md
    - EnergyPlus Guides:
      - Simple EnergyPlus simulation: how-to/guide_ep1.md
      - EnergyPlus Guide 2: how-to/guide_ep2.md
      - EnergyPlus Guide 3: how-to/guide_ep3.md
    - Radiance Guides:
      - Radiance Guide 1: how-to/guide_rad1.md
      - Radiance Guide 2: how-to/guide_rad2.md
      - Radiance Guide 3: how-to/guide_rad3.md
      - Radiance Guide 7: how-to/guide_rad7.md
    - Combined Guides:
      - Radiance-EnergyPlus Guide 1: how-to/guide_radep1.md
      - Radiance-EnergyPlus Guide 2: how-to/guide_radep2.md
      - Radiance-EnergyPlus Guide 3: how-to/guide_radep3.md

  - Reference:
    - WorkflowConfig: ref/config.md
    - TwoPhaseMethod: ref/twophase.md
    - ThreePhaseMethod: ref/threephase.md
    - FivePhaseMethod: ref/fivephase.md
    - matrix: ref/matrix.md
    - EnergyPlus: ref/eplus.md
    - GlazingSystem: ref/window.md
    - Sky: ref/sky.md

